run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 140
  
  goimports:
    local-prefixes: github.com/smallbiznis/railzway-cloud
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - unnamedResult
  
  funlen:
    lines: 100
    statements: 50
  
  nestif:
    min-complexity: 4
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: true
      - name: unexported-return
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - gocritic
    - funlen
    - nestif
    - exportloopref
    - nolintlint

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - funlen
        - goconst
    
    # Exclude known issues in generated code
    - path: mock_.*\.go
      linters:
        - revive
        - stylecheck
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
